### ISSUE TITLE
Avien docker image Failed to open the storage [lensesdb]

### ISSUE THREAD

**Issue by JustinMoser** [lensesio/lenses-docker#22]
I am following your guide on getting lenses running locally using my Avien Kafka cluster from this page:

https://docs.lenses.io/install_setup/deployment-options/aiven-deployment.html#cloud-aiven-docker-compose-example

However when i run `docker-compose up`, it gets most of the way through the process but then fails with the following error:

```
2019-10-11 16:24:57,093 INFO  [i.l.r.H2ConnectionBuilder$:27] Setting the local storage to [/data/storage]
lenses_1  | 2019-10-11 16:24:57,094 INFO  [i.l.r.H2ConnectionBuilder$:27] Setting the local storage to [/data/storage]
lenses_1  | 2019-10-11 16:24:57,094 INFO  [i.l.r.H2ConnectionBuilder$:43] Opening the storage to lensesdb...
lenses_1  | 2019-10-11 16:24:57,617 ERROR [i.l.r.H2ConnectionBuilder$:48] Failed to open the storage [lensesdb].
lenses_1  | org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known" [90028-199]
lenses_1  | 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
lenses_1  | 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
lenses_1  | 	at org.h2.message.DbException.get(DbException.java:194)
lenses_1  | 	at org.h2.message.DbException.convert(DbException.java:339)
lenses_1  | 	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:254)
lenses_1  | 	at org.h2.server.TcpServer.getURL(TcpServer.java:199)
lenses_1  | 	at org.h2.tools.Server.start(Server.java:512)
lenses_1  | 	at org.h2.engine.Database.startServer(Database.java:958)
lenses_1  | 	at org.h2.engine.Database.open(Database.java:736)
lenses_1  | 	at org.h2.engine.Database.openDatabase(Database.java:319)
lenses_1  | 	at org.h2.engine.Database.<init>(Database.java:313)
lenses_1  | 	at org.h2.engine.Engine.openSession(Engine.java:69)
lenses_1  | 	at org.h2.engine.Engine.openSession(Engine.java:201)
lenses_1  | 	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
lenses_1  | 	at org.h2.engine.Engine.createSession(Engine.java:161)
lenses_1  | 	at org.h2.engine.Engine.createSession(Engine.java:31)
lenses_1  | 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
lenses_1  | 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
lenses_1  | 	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
lenses_1  | 	at org.h2.Driver.connect(Driver.java:69)
lenses_1  | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
lenses_1  | 	at java.sql.DriverManager.getConnection(DriverManager.java:270)
lenses_1  | 	at io.lenses.runtime.H2ConnectionBuilder$.apply(H2ConnectionBuilder.scala:45)
lenses_1  | 	at com.landoop.kafka.lenses.Main$.delayedEndpoint$com$landoop$kafka$lenses$Main$1(Main.scala:194)
lenses_1  | 	at com.landoop.kafka.lenses.Main$delayedInit$body.apply(Main.scala:147)
lenses_1  | 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
lenses_1  | 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
lenses_1  | 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
lenses_1  | 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
lenses_1  | 	at scala.collection.immutable.List.foreach(List.scala:392)
lenses_1  | 	at scala.App.main(App.scala:80)
lenses_1  | 	at scala.App.main$(App.scala:78)
lenses_1  | 	at com.landoop.kafka.lenses.Main$.main(Main.scala:147)
lenses_1  | 	at com.landoop.kafka.lenses.Main.main(Main.scala)
lenses_1  | Caused by: java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known
lenses_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
lenses_1  | 	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:252)
lenses_1  | 	... 29 common frames omitted
lenses_1  | Caused by: java.net.UnknownHostException: linuxkit-025000000001: Name or service not known
lenses_1  | 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
lenses_1  | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
lenses_1  | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
lenses_1  | 	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
lenses_1  | 	... 30 common frames omitted
lenses_1  | 2019-10-11 16:24:57,619 INFO  [i.l.r.H2ConnectionBuilder$:49] Lenses shut down.
```

Any ideas?

Thank you.

**Comment by andmarios** [comment]
Hi @JustinMoser, try to remote this line from the docker-compose:
```
    network_mode: host
```

I think you may be on Docker for Mac, which doesn't support the host network mode.

**Comment by JustinMoser** [comment]
Thanks, that was the issue.
