### ISSUE TITLE
[Redis-Sink] No writers set for connect.redis.kcql

### ISSUE THREAD

**Issue by albvol** [lensesio/lenses-docker#36]
Hello, I am trying to set up a Redis Sink connector on the lenses dashboard.
In particular, I am using the following version:
- Lenses 3.2.1
- Kafka 2.2.2-L0

The configuration is the following one:
```
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
connect.redis.port=6370
connect.redis.kcql=INSERT INTO table1 SELECT * FROM topic1_test
topics= topic1_test
tasks.max=1
connect.redis.host=172.17.0.4
name=redis-sink
```

The related task shows the following error:
```
java.lang.IllegalArgumentException: requirement failed: No writers set for connect.redis.kcql!
	at scala.Predef$.require(Predef.scala:224)
	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.start(RedisSinkTask.scala:97)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any suggestion? Thanks.

**Comment by albvol** [comment]
As suggested [here](https://github.com/lensesio/stream-reactor/issues/312) the solution is to change the connect.redis.kcql properties.

In my case, I changed it from: 
`INSERT INTO table1 SELECT * FROM topic1_test`
to:
`INSERT INTO table1 SELECT * FROM topic1_test PK <key>`
