### ISSUE TITLE
ERROR! Lenses port (LENSES_PORT=9991) is in use by some other program.

### ISSUE THREAD

**Issue by jamesbmorris92** [lensesio/lenses-docker#40]
I'm trying to run the lenses locally on my mac. However every time I try to start the container I get the following error:

"Initializing environment —docker setup script.
LENSES_SECURITY_PASSWORD is not set. You may be using the default password which is dangerous.
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x512269, 0x9)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420028000, 0xc420037fc0)
	/usr/lib/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x5203a0, 0x0)
	/usr/lib/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/lib/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x593600)
	/usr/lib/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760
runtime.main()
	/usr/lib/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0
ERROR! Lenses port (LENSES_PORT=9991) is in use by some other program.
       Lenses will probably fail to start.
lenses.port=9991
[Variable needed quotes] lenses.sql.state.dir=/data/kafka-streams-state
Running as root. Will change data ownership to nobody:nogroup (65534:65534)
and drop priviliges.
Setup script finished.
Docker environment initialized. Starting Lenses.
================================================
Initializing (pre-run) Lenses
Installation directory autodetected: /opt/lenses
Current directory: /data
Logback configuration file autodetected: logback.xml
/usr/bin/find: '/opt/lenses/plugins': No such file or directory
These directories will be monitored for new jar files:
 - /opt/lenses/plugins
 - /data/plugins
 - /opt/lenses/serde
Starting application
Error: LinkageError occurred while loading main class io.lenses.backend.Main
	java.lang.ClassFormatError: Incompatible magic value 1447843890 in class file io/lenses/backend/Main
Initializing environment —docker setup script.
LENSES_SECURITY_PASSWORD is not set. You may be using the default password which is dangerous.
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x512269, 0x9)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420028000, 0xc420037fc0)
	/usr/lib/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x5203a0, 0x0)
	/usr/lib/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/lib/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x593600)
	/usr/lib/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760
runtime.main()
	/usr/lib/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0
ERROR! Lenses port (LENSES_PORT=9991) is in use by some other program.
       Lenses will probably fail to start.
lenses.port=9991
[Variable needed quotes] lenses.sql.state.dir=/data/kafka-streams-state
Running as root. Will change data ownership to nobody:nogroup (65534:65534)
and drop priviliges.
Setup script finished.
Docker environment initialized. Starting Lenses.
================================================
Initializing (pre-run) Lenses
Installation directory autodetected: /opt/lenses
Current directory: /data
Logback configuration file autodetected: logback.xml
/usr/bin/find: '/opt/lenses/plugins': No such file or directory
These directories will be monitored for new jar files:
 - /opt/lenses/plugins
 - /data/plugins
 - /opt/lenses/serde
Starting application
Error: LinkageError occurred while loading main class io.lenses.backend.Main
	java.lang.ClassFormatError: Incompatible magic value 1447843890 in class file io/lenses/backend/Main"

I've tried a few different ports and they all have the same issue. I'm using docker compose to create my container using the following:
`  lenses:
    image: lensesio/lenses
    platform: linux/amd64
    networks:
      - app-tier
    environment:
      - LENSES_PORT=9991
    ports:
      - 9991:9991`

The mac i'm running on locally is a newer model with an M1 chip

**Comment by khmelevskii** [comment]
+1

**Comment by leozleung** [comment]
+1, using mac M1 chip as well

**Comment by diegoep** [comment]
+1, using mac M1 chip as well

**Comment by Thilakforabm** [comment]
were any of you able to resolve this ?, any help is  much appreciated
lenses image :4.3 gives this error, if i try a more latest image (5.0+)with lenses.conf as a mounted volume i get a parsing error even when the file is empty,
